name: BTS Ticket Reminder

on:
  schedule:
    - cron: '* * * * *'

jobs:
  check_time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install requests
        run: pip install requests
      - name: Run Reminder
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python reminder.py